is it okay now ? ( Bengali Facts)
wh-iterabb-it/meowfacts pull request #326
Opened 2023-09-26 05:14 UTC by dshaw0004

I run the `npm run test:lint:fix` on node v16. Hope it is fixed now.

2023-09-26 05:33 UTC, dshaw0004 commented
even after running `npm run test:lint:fix` it was not fixed so I have to copy the whitespace from `eng-us.js` then paste it to `ben-in.js`.

2023-09-29 15:52 UTC, BeauBouchard requested changes
I think this is an excellent contribution, Thank you for making changes in a new branch, it makes it a lot cleaner. 

This would be fine to merge if it didn't include the `replit.nix` and `.replit` files, you can remove them by deleting them, and `git add -A` then making a new commit / push. 

Once again thank you for your continued contribution and efforts on this localization.

2023-09-29 15:52 UTC, BeauBouchard commented on replit.nix
> +{ pkgs }: {
lets just remove this file, and the other `.replit` file

2023-09-29 15:59 UTC, dshaw0004 commented
okay

2023-09-29 16:03 UTC, dshaw0004 commented
its done. sorry I didn't noticed that.

2023-10-01 11:04 UTC, BeauBouchard approved these changes
Great job!

2023-10-01 11:05 UTC, merged